### ISSUE TITLE
Bugs in distributedCalcMex ?

### ISSUE THREAD

**Issue by djw77** [slambrick/SHeM-Ray-Tracing-Simulation#13]
Running performscattering.m causes an error because  on line 58 of distributionCalc the call to distributionCalcMex has 12 arguments and in that mex file the check is for 11 arguments (line 83 of that file). Also in line 122 of distributedCalcMex  I think it should be  mxGetN(prhs[10]) rather than  mxGetN(prhs[9]).

**Comment by slambrick** [comment]
This should now be solved, there were further errors to fix alongside the number of arguments
